export namespace fast_io
{
    using ::fast_io::win32_stdout_number;
    using ::fast_io::win32_stderr_number;

    namespace win32
    {
        using ::fast_io::win32::GetStdHandle;
        using ::fast_io::win32::GetStdHandle;
        using ::fast_io::win32::GetConsoleMode;
        using ::fast_io::win32::SetConsoleMode;
        using ::fast_io::win32::GetConsoleCP;
        using ::fast_io::win32::GetConsoleOutputCP;
        using ::fast_io::win32::SetConsoleCP;
        using ::fast_io::win32::SetConsoleOutputCP;
    } // namespace win32
}